name: VanillaChatter
main: me.greaperc4.VC.VanillaChatter
version: 1.1.1
author: greaperc4
description: Made by greaperc4.

commands:
  vanillachatter:
    description: shows all the commands
    aliases: [vc]
    
permissions:
  vanillachatter.admin:
    description: parent permission.
    children:
      vanillachatter.admin.set: true
      vanillachatter.admin.clear: true
      vanillachatter.admin.prefix: true
      vanillachatter.admin.setnick: true
      vanillachatter.admin.setcolor: true
      vanillachatter.admin.setprefix: true
      vanillachatter.admin.mute: true
      vanillachatter.admin.unmute: true
      vanillachatter.admin.colorlist: true
  vanillachatter.admin.set:
    description: parent permissions for set command.
    children:
      vanillachatter.admin.setnick: true
      vanillachatter.admin.setcolor: true
      vanillachatter.admin.setprefix: true
  vanillachatter.admin.mute:
    description: acces to mute and unmute command
    children:
      vanillachatter.admin.mute: true
      vanillachatter.admin.unmute: true
